all: random entradaTeclado dado placar rolaDados
	javac -sourcepath src -cp bin -d bin src/Bozo.java

run:
	java -cp bin Bozo

random:
	javac -d bin -sourcepath src src/Random.java

entradaTeclado:
	javac -d bin -sourcepath src src/EntradaTeclado.java

dado:
	javac -d bin -sourcepath src src/Dado.java

placar:
	javac -d bin -sourcepath src src/Placar.java

rolaDados:
	javac -d bin -sourcepath src src/RolaDados.java